name: Wave
options:
  bundleIdPrefix: app.wave
  deploymentTarget:
    iOS: '17.0'
settings:
  base:
    SWIFT_VERSION: '5.0'
    TARGETED_DEVICE_FAMILY: '1,2'
schemes:
  Wave:
    build:
      targets:
        Wave: all
    test:
      targets: [WaveTests]
targets:
  Wave:
    type: application
    platform: iOS
    sources: [Wave, Shared]
    entitlements:
      path: Wave/Wave.entitlements
      properties:
        com.apple.security.application-groups: [group.app.wave.music]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.wave.music.ios
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited) WAVE_APP"
        MARKETING_VERSION: '0.11.5'
        CURRENT_PROJECT_VERSION: '33'
    dependencies:
      - target: WaveWidgets
        embed: true
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Wave
        CFBundleURLTypes:
          - CFBundleURLName: app.wave.music.ios
            CFBundleURLSchemes: [wave]
        NSAppleMusicUsageDescription: Wave necesita acceso para mostrar y reproducir las canciones, álbumes y playlists de tu biblioteca de Música.
        UILaunchScreen: {}
        UIBackgroundModes: [audio]
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
  WaveWidgets:
    type: app-extension
    platform: iOS
    sources: [WaveWidgets, Shared]
    entitlements:
      path: WaveWidgets/WaveWidgets.entitlements
      properties:
        com.apple.security.application-groups: [group.app.wave.music]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.wave.music.ios.widgets
        MARKETING_VERSION: '0.11.5'
        CURRENT_PROJECT_VERSION: '33'
        APPLICATION_EXTENSION_API_ONLY: YES
        SKIP_INSTALL: YES
    info:
      path: WaveWidgets/Info.plist
      properties:
        CFBundleDisplayName: Wave Widgets
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
  WaveTests:
    type: bundle.unit-test
    platform: iOS
    sources: [WaveTests]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Wave
