const {app,BrowserWindow,dialog,net,Menu}=require('electron');
const fs=require('node:fs/promises');const sync=require('node:fs');const os=require('node:os');const path=require('node:path');const http=require('node:http');const assert=require('node:assert/strict');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let fixture,temp;
async function waitFor(win,expression,label){for(let i=0;i<100;i++){if(await win.webContents.executeJavaScript(expression))return;await delay(60);}throw Error('Timeout: '+label);}
(async()=>{
  temp=sync.mkdtempSync(path.join(os.tmpdir(),'wave-smoke-'));const user=path.join(temp,'settings');sync.mkdirSync(user);app.setPath('userData',user);
  const folder=path.join(temp,'Music');sync.mkdirSync(folder);sync.mkdirSync(path.join(folder,'Album A'));sync.mkdirSync(path.join(folder,'Album B'));const outside=path.join(temp,'Other');sync.mkdirSync(outside);
  const wav=Buffer.alloc(44+44100*2*12);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(44100,24);wav.writeUInt32LE(88200,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);
  for(let i=0;i<44100*12;i++)wav.writeInt16LE(Math.round(Math.sin(i*2*Math.PI*220/44100)*(6000+4000*Math.sin(i/44100))),44+i*2);
  sync.writeFileSync(path.join(folder,'Root.wav'),wav);sync.writeFileSync(path.join(folder,'Album A','Same.wav'),wav);sync.writeFileSync(path.join(folder,'Album A','Extra.wav'),wav);sync.writeFileSync(path.join(folder,'Album B','Same.wav'),'old audio');sync.writeFileSync(path.join(folder,'notes.txt'),'not music');
  sync.writeFileSync(path.join(folder,'Album B','cover.png'),Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aF1sAAAAASUVORK5CYII=','base64'));
  const calls=[];let state={hidden:[],orders:{}};const port=35000+process.pid%20000;
  fixture=http.createServer(async(req,res)=>{
    calls.push(req.url);res.setHeader('Content-Type','application/json');const answer=value=>res.end(JSON.stringify(value));
    if(req.url==='/wave/api/likes')return answer({});
    if(req.url==='/wave/api/folders')return answer([{name:'Server Album',count:2}]);
    if(req.url==='/wave/api/desktop/state'){
      if(req.method==='POST'){let body='';for await(const part of req)body+=part;const operation=JSON.parse(body);if(operation.action==='hidden'){const hidden=new Set(state.hidden);operation.paths.forEach(p=>operation.hidden?hidden.add(p):hidden.delete(p));state.hidden=[...hidden];}else state.orders[operation.scope]=operation.paths;}
      return answer(state);
    }
    if(req.url==='/wave/api/folder/Server%20Album/tracks')return answer(['First','Second'].map(name=>({name,artist:'Wave Artist',filename:name+'.wav',relPath:'Server Album/'+name+'.wav',url:'/music/Server%20Album/'+name+'.wav',duration:12,play_count:2})));
    if(req.url==='/wave/api/play')return answer({count:3});
    if(req.url==='/wave/api/spotify/status')return answer({configured:true});
    if(req.url==='/wave/api/spotify/search-token')return answer({access_token:'temporary-smoke-token',expires_in:3600});
    if(req.url.startsWith('/wave/music/')){
      res.setHeader('Content-Type','audio/wav');res.setHeader('Accept-Ranges','bytes');let start=0,end=wav.length-1;
      if(req.headers.range){const match=/bytes=(\d+)-(\d*)/.exec(req.headers.range);if(match){start=Number(match[1]);if(match[2])end=Number(match[2]);res.statusCode=206;res.setHeader('Content-Range',`bytes ${start}-${end}/${wav.length}`);}}
      res.setHeader('Content-Length',end-start+1);return res.end(req.method==='HEAD'?undefined:wav.subarray(start,end+1));
    }
    res.statusCode=404;answer({error:'Unknown fixture endpoint'});
  }).listen(port,'127.0.0.1');
  sync.writeFileSync(path.join(user,'settings.json'),JSON.stringify({server:`http://127.0.0.1:${port}/wave/`}));
  const originalFetch=net.fetch.bind(net);net.fetch=async(url,options)=>{
    if(String(url).startsWith('https://api.spotify.com/v1/search'))return new Response(JSON.stringify({tracks:{items:[{id:'4BsmokeTrack',name:'Around the World',artists:[{name:'Daft Punk'}],album:{name:'Homework',images:[]},duration_ms:429000,external_urls:{spotify:'https://open.spotify.com/track/4BsmokeTrack'}}],total:1,next:null}}),{headers:{'Content-Type':'application/json'}});
    return originalFetch(url,options);
  };
  let picker=folder;dialog.showOpenDialog=async()=>({canceled:picker===null,filePaths:picker?[picker]:[]});
  require('../main.cjs');await app.whenReady();let win;
  for(let i=0;i<100;i++){win=BrowserWindow.getAllWindows()[0];if(win&&win.webContents.getURL().endsWith('ui/index.html')&&!win.webContents.isLoading())break;await delay(60);}
  const js=code=>win.webContents.executeJavaScript(code);
  await waitFor(win,"document.querySelectorAll('.folder-card').length===1",'server folders');
  assert.equal(await js("view"),'advanced');assert.equal(await js("browserLayout"),'columns');assert.equal(await js("document.getElementById('table-wrap').hidden"),true);
  await js("setView('normal');document.getElementById('list-layout').click()");
  assert.equal(win.contentView.children.length,0,'No embedded server web view');
  await js("document.querySelector('.folder-card').click()");await waitFor(win,"document.querySelectorAll('.track').length===2",'server tracks');
  await js("document.querySelector('.song-title').click()");await waitFor(win,"!document.getElementById('audio').paused",'server playback');
  const serverAudio=await js("document.getElementById('audio').src");assert.match(serverAudio,/wave-audio:\/\/server\//);assert.equal((await net.fetch(serverAudio)).status,200);
  await js("document.getElementById('open-song').click()");await waitFor(win,"document.getElementById('waveform-status').textContent.includes('Haz clic')",'server waveform');await js("document.getElementById('song-close').click()");
  await js("document.querySelector('.row-actions button[aria-label^=\"Ocultar\"]').click()");await waitFor(win,"document.querySelectorAll('.track').length===1",'hide server song');assert.equal(state.hidden.length,1);
  await js("document.getElementById('advanced-view').click()");await waitFor(win,"document.querySelectorAll('.track.is-hidden').length===1",'advanced hidden server');
  await js("document.querySelector('.is-hidden button[aria-label^=\"Mostrar\"]').click()");await waitFor(win,"document.querySelectorAll('.track.is-hidden').length===0",'restore server song');
  await js("document.querySelector('.row-actions button[aria-label^=\"Bajar\"]').click()");await waitFor(win,"document.querySelector('.song-title strong').textContent==='Second'",'server order saved');assert.equal(state.orders['Server Album'][0],'Server Album/Second.wav');
  await js("window.wave.switchSource('local')");await waitFor(win,"document.getElementById('local-nav').classList.contains('active')",'local source');assert.equal(await js("document.getElementById('audio').paused"),false);assert.equal(await js("document.getElementById('audio').src"),serverAudio);
  await js("document.getElementById('play').click()");assert.equal(await js("document.getElementById('audio').paused"),true);
  await js("document.getElementById('play').click()");await waitFor(win,"!document.getElementById('audio').paused",'resume across libraries');
  await js("document.getElementById('next').click()");await waitFor(win,"document.getElementById('now-title').textContent==='Second'",'original server queue across libraries');
  await js("window.wave.switchSource('settings')");await waitFor(win,"!document.getElementById('settings').hidden",'settings during playback');assert.equal(await js("document.getElementById('audio').paused"),false);
  await js("window.wave.switchSource('local')");await waitFor(win,"document.getElementById('local-nav').classList.contains('active')",'return to local');
  await js("document.getElementById('choose').click()");await waitFor(win,"document.querySelectorAll('.folder-card').length===2",'local folder explorer');assert.equal(await js("document.querySelectorAll('.track').length"),1);
  await js("[...document.querySelectorAll('.folder-card')].find(b=>b.textContent.includes('Album A')).click()");await waitFor(win,"document.querySelectorAll('.track').length===2",'nested folder songs');
  const editMenu=Menu.getApplicationMenu().items.find(item=>item.label==='Edición').submenu;editMenu.items.find(item=>item.label==='Seleccionar todo').click();await waitFor(win,"document.getElementById('selection-count').textContent.includes('2')",'native select all');editMenu.items.find(item=>item.label==='Copiar').click();await waitFor(win,"document.querySelectorAll('.tray-item').length===2",'copy tray');
  await js("[...document.querySelectorAll('.tree-node')].find(b=>b.textContent.startsWith('Album B')).click()");await waitFor(win,"document.querySelectorAll('.track').length===1",'destination folder');
  editMenu.items.find(item=>item.label==='Pegar').click();await waitFor(win,"document.querySelectorAll('.track').length===2&&document.getElementById('tray-notice').textContent.includes('sobrescritas')",'paste with overwrite');
  assert.deepEqual(await fs.readFile(path.join(folder,'Album B','Same.wav')),wav);assert.deepEqual(await fs.readFile(path.join(folder,'Album B','Extra.wav')),wav);
  picker=outside;await js("document.getElementById('paste-elsewhere').click()");await waitFor(win,"!document.getElementById('paste-elsewhere').disabled",'paste arbitrary selected destination');assert.deepEqual(await fs.readFile(path.join(outside,'Same.wav')),wav);
  await js("document.querySelector('.row-actions button[aria-label^=\"Bajar\"]').click()");await waitFor(win,"document.querySelector('.song-title strong').textContent==='Same'",'local persistent order');
  await js("document.querySelector('.row-actions button[aria-label^=\"Ocultar\"]').click()");await waitFor(win,"document.querySelectorAll('.track.is-hidden').length===1",'local hide advanced');
  await js("document.getElementById('normal-view').click()");assert.equal(await js("document.querySelectorAll('.track').length"),1);assert.ok(sync.existsSync(path.join(folder,'Album B','Same.wav')));
  await js("document.getElementById('refresh').click()");await waitFor(win,"!document.getElementById('refresh').disabled&&document.querySelectorAll('.track').length===1",'hidden persists after rescan');
  const saved=JSON.parse(await fs.readFile(path.join(folder,'.wave-library.json'),'utf8'));assert.deepEqual(saved.orders['Album B'],['Album B/Same.wav','Album B/Extra.wav']);assert.deepEqual(saved.hidden,['Album B/Same.wav']);
  await js("document.getElementById('advanced-view').click()");assert.equal(await js("document.querySelectorAll('.track').length"),2);
  await js("document.querySelector('.is-hidden button[aria-label^=\"Mostrar\"]').click()");await waitFor(win,"document.querySelectorAll('.track.is-hidden').length===0",'restore local song');
  await js("document.querySelector('.song-title').click()");await waitFor(win,"!document.getElementById('audio').paused",'local playback');
  const localAudio=await js("document.getElementById('audio').src");const range=await net.fetch(localAudio,{headers:{Range:'bytes=44-100'}});assert.equal(range.status,206);assert.equal((await range.arrayBuffer()).byteLength,57);
  await js("document.getElementById('audio').currentTime=5");await delay(100);assert.ok(await js("document.getElementById('audio').currentTime>=5"));
  await js("document.getElementById('column-layout').click()");assert.equal(await js("document.getElementById('column-browser').hidden"),false);assert.equal(await js("document.querySelectorAll('.finder-column').length"),2);
  assert.equal(await js("getComputedStyle(document.querySelector('.advanced-only')).display"),'table-cell');
  assert.equal(await js("document.getElementById('table-wrap').hidden"),true);
  await js("document.getElementById('search').value='';renderLibrary()");
  const dragBefore=await js("visibleTracks().map(track=>track.id)");
  await js("(()=>{const rows=[...document.querySelectorAll('.finder-column:last-child .column-track')];const data=new DataTransfer();rows[0].dispatchEvent(new DragEvent('dragstart',{dataTransfer:data,bubbles:true}));rows[1].dispatchEvent(new DragEvent('dragover',{dataTransfer:data,bubbles:true,cancelable:true}));rows[1].dispatchEvent(new DragEvent('drop',{dataTransfer:data,bubbles:true,cancelable:true}));})()");
  await waitFor(win,"!working",'column drag saves order');assert.deepEqual(await js("visibleTracks().map(track=>track.id)"),dragBefore.reverse());
  assert.ok(await js("document.querySelector('.finder-column:last-child .track-cover')!==null"));
  assert.match(await js("window.wave.artwork('local',visibleTracks()[0].id)"),/^data:image\/png;base64,/);
  assert.equal(await js("document.getElementById('navigate-back').querySelector('use').getAttribute('href')"),'#i-arrow-left');
  await js("window.wave.windowControl('minimize')");await delay(100);win.restore();
  assert.ok(Array.isArray(await js("window.wave.volumes()")));await assert.rejects(js("window.wave.openVolume('/etc')"));
  await delay(120);const explorerShot=await win.webContents.capturePage();await fs.writeFile('/tmp/wave-columns.png',explorerShot.toPNG());
  await js("document.getElementById('compact-player').click()");assert.equal(await js("document.getElementById('player').classList.contains('compact')"),true);
  await js("document.getElementById('volume').value='0.4';document.getElementById('volume').dispatchEvent(new Event('input'))");assert.equal(await js("document.getElementById('audio').volume"),0.4);
  await js("document.getElementById('open-song').click()");await waitFor(win,"!document.getElementById('song-view').hidden",'dedicated song view');
  await waitFor(win,"document.getElementById('waveform-status').textContent.includes('Haz clic')",'decoded real waveform');
  await js("document.getElementById('song-seek').value='500';document.getElementById('song-seek').dispatchEvent(new Event('input'))");assert.ok(await js("document.getElementById('audio').currentTime>=6"));
  assert.equal(await js("document.getElementById('song-title').textContent"),await js("document.getElementById('now-title').textContent"));
  await delay(120);const songShot=await win.webContents.capturePage();await fs.writeFile('/tmp/wave-song.png',songShot.toPNG());
  win.minimize();await delay(150);assert.equal(await js("document.getElementById('audio').paused"),false);win.restore();
  await js("document.getElementById('song-close').click()");assert.equal(await js("document.getElementById('library').hidden"),false);assert.equal(await js("document.getElementById('audio').paused"),false);
  await js("document.getElementById('refresh').click()");await waitFor(win,"!document.getElementById('refresh').disabled",'refresh while playing');assert.equal(await js("document.getElementById('audio').paused"),false);
  const screenshot=await win.webContents.capturePage();await fs.writeFile('/tmp/wave-1.1-local.png',screenshot.toPNG());
  picker=null;assert.equal(await js("window.wave.chooseFolder()"),null);
  await assert.rejects(js("window.wave.paste({folder:'../'})"));await assert.rejects(js("window.wave.saveServer('file:///tmp')"));
  await js("window.wave.switchSource('spotify')");await waitFor(win,"!document.getElementById('spotify').hidden",'Spotify section');
  await js("document.getElementById('spotify-query').value='Daft Punk';document.getElementById('spotify-form').requestSubmit()");await waitFor(win,"document.querySelectorAll('.spotify-result').length===1",'Spotify catalog search fixture');
  assert.equal(await js("document.getElementById('audio').paused"),false);
  assert.equal(await js("document.querySelector('.spotify-result strong').textContent"),'Around the World');assert.equal(await js("document.body.textContent.includes('temporary-smoke-token')"),false);assert.equal(await js("typeof window.require"),'undefined');
  assert.ok(calls.every(url=>url.startsWith('/wave/api/')||url.startsWith('/wave/music/')),'No server HTML requested');
  const spotifyShot=await win.webContents.capturePage();await fs.writeFile('/tmp/wave-1.1-spotify.png',spotifyShot.toPNG());
  await js("window.wave.switchSource('local')");await waitFor(win,"!document.getElementById('library').hidden",'navigation local source');
  await js("document.getElementById('audio').loop=true;document.getElementById('search').value='';browserLayout='list';setView('normal');navigate('');navigationHistory.length=0;navigationIndex=-1;recordNavigation()");
  const continuousAudio=await js("document.getElementById('audio').src");
  await js("navigate('Album A')");assert.equal(await js("navigationIndex"),1);
  await js("document.getElementById('search').value='Extra';document.getElementById('search').dispatchEvent(new Event('input'));navigate('Album B')");
  assert.equal(await js("navigationIndex"),2);
  await js("document.getElementById('navigate-back').click()");await waitFor(win,"!restoringNavigation&&libraries.local.path==='Album A'",'back restores folder');
  assert.equal(await js("document.getElementById('search').value"),'Extra');assert.equal(await js("document.querySelectorAll('.track').length"),1);
  await js("document.getElementById('navigate-forward').click()");await waitFor(win,"!restoringNavigation&&libraries.local.path==='Album B'",'forward restores folder');
  const viewMenu=Menu.getApplicationMenu().items.find(item=>item.label==='Visualización').submenu;
  viewMenu.items.find(item=>item.label==='Atrás').click();await waitFor(win,"!restoringNavigation&&libraries.local.path==='Album A'",'native back accelerator');
  viewMenu.items.find(item=>item.label==='Adelante').click();await waitFor(win,"!restoringNavigation&&libraries.local.path==='Album B'",'native forward accelerator');
  await js("document.querySelector('main').dispatchEvent(new WheelEvent('wheel',{deltaX:-110,deltaY:1,bubbles:true,cancelable:true}));document.querySelector('main').dispatchEvent(new WheelEvent('wheel',{deltaX:-110,deltaY:1,bubbles:true,cancelable:true}));document.querySelector('main').dispatchEvent(new WheelEvent('wheel',{deltaX:-110,deltaY:1,bubbles:true,cancelable:true}))");
  await waitFor(win,"!restoringNavigation&&libraries.local.path==='Album A'",'trackpad back once per gesture');assert.equal(await js("navigationIndex"),1);
  await js("document.getElementById('navigate-forward').click()");await waitFor(win,"!restoringNavigation&&libraries.local.path==='Album B'",'forward after swipe');
  await js("document.getElementById('search').dispatchEvent(new WheelEvent('wheel',{deltaX:-300,bubbles:true,cancelable:true}));document.querySelector('main').dispatchEvent(new WheelEvent('wheel',{deltaX:2,deltaY:110,bubbles:true,cancelable:true}))");assert.equal(await js("navigationIndex"),2);
  await js("document.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',altKey:true,bubbles:true,cancelable:true}))");await waitFor(win,"!restoringNavigation&&libraries.local.path==='Album A'",'Alt-left navigation');
  await js("document.dispatchEvent(new MouseEvent('auxclick',{button:4,bubbles:true,cancelable:true}))");await waitFor(win,"!restoringNavigation&&libraries.local.path==='Album B'",'mouse forward button');
  await delay(700);win.emit('swipe',{},'right');await waitFor(win,"!restoringNavigation&&libraries.local.path==='Album A'",'native macOS swipe routed');
  await js("document.getElementById('navigate-forward').click()");await waitFor(win,"!restoringNavigation&&libraries.local.path==='Album B'",'forward after native gesture');
  await delay(700);await js("document.querySelector('main').dispatchEvent(new PointerEvent('pointerdown',{pointerType:'touch',isPrimary:true,pointerId:7,clientX:300,clientY:400,bubbles:true}));document.querySelector('main').dispatchEvent(new PointerEvent('pointerup',{pointerType:'touch',isPrimary:true,pointerId:7,clientX:410,clientY:405,bubbles:true}))");
  await waitFor(win,"!restoringNavigation&&libraries.local.path==='Album A'",'touch swipe navigation');
  await js("navigate('');document.getElementById('search').value='';document.getElementById('open-song').click()");assert.equal(await js("document.getElementById('song-view').hidden"),false);
  await js("document.getElementById('navigate-back').click()");await waitFor(win,"!restoringNavigation&&document.getElementById('song-view').hidden",'back closes song view');
  await js("document.getElementById('navigate-forward').click()");await waitFor(win,"!restoringNavigation&&!document.getElementById('song-view').hidden",'forward restores song view');
  await js("document.getElementById('song-close').click();navigate('Album B');setView('advanced');document.getElementById('column-layout').click()");
  const beforeColumnScroll=await js("navigationIndex");
  await js("document.getElementById('column-browser').style.maxWidth='280px';document.getElementById('column-browser').dispatchEvent(new WheelEvent('wheel',{deltaX:-300,bubbles:true,cancelable:true}))");assert.equal(await js("navigationIndex"),beforeColumnScroll,'Horizontal column scrolling must not navigate');
  await js("document.getElementById('column-browser').style.maxWidth='';document.getElementById('navigate-back').click()");await waitFor(win,"!restoringNavigation&&browserLayout==='list'",'back restores list layout');
  await js("document.getElementById('navigate-forward').click()");await waitFor(win,"!restoringNavigation&&browserLayout==='columns'",'forward restores column layout');
  await js("document.getElementById('navigate-back').click()");await waitFor(win,"!restoringNavigation&&browserLayout==='list'",'branch previous route');
  await js("navigate('Album A')");assert.equal(await js("document.getElementById('navigate-forward').disabled"),true,'A new route replaces the forward branch');
  assert.equal(await js("document.getElementById('audio').paused"),false);assert.equal(await js("document.getElementById('audio').src"),continuousAudio);
  await js("document.dispatchEvent(new PointerEvent('pointerdown',{pointerType:'mouse',bubbles:true}));navigate('Album B')");
  assert.equal(await js("document.querySelector('main>section:not([hidden])').getAnimations().length"),0,'Navigation is immediate');
  await js("toggleTray(true);toggleTray(false);toggleTray(true)");await delay(250);assert.equal(await js("document.getElementById('tray').hidden"),false,'Rapid tray toggles stay open');
  win.webContents.debugger.attach('1.3');await win.webContents.debugger.sendCommand('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
  await js("navigate('Album A');toggleTray(false)");assert.equal(await js("document.getElementById('tray').hidden"),true);assert.equal(await js("getComputedStyle(document.getElementById('play')).transitionDuration"),'0s');assert.equal(await js("document.getAnimations().length"),0);
  await win.webContents.debugger.sendCommand('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});win.webContents.debugger.detach();
  await js("document.getElementById('audio').loop=false");await delay(250);
  const navigationShot=await win.webContents.capturePage();await fs.writeFile('/tmp/wave-1.3-navigation.png',navigationShot.toPNG());
  console.log('PASS: historial atrás/adelante, trackpad sin saltos múltiples, gestos nativos y táctiles, atajos, desplazamiento horizontal, restauración de filtros/vistas/canción, ramificación de historial, navegación inmediata, movimiento reducido, Spotify conservado, reproducción continua entre pestañas y minimizada, cola independiente, onda real servidor/local, búsqueda temporal, volumen, modo compacto, listas y columnas, interfaz nativa/API, carpetas, reproducción servidor/local, orden persistente, ocultar/recuperar, bandeja, sobrescritura real, destino elegido, cancelación, aislamiento y búsqueda Spotify simulada.');
  fixture.close();await fs.rm(temp,{recursive:true,force:true});app.exit(0);
})().catch(error=>{console.error(error);fixture?.close();app.exit(1);});
